/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package j2_s_p0001;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Nguyen Vu Khang CE140224
 */
public class J2_S_P0001 extends javax.swing.JFrame {
    
    
    /**
     * Creates new form J2_S_P0001
     */
    public J2_S_P0001() {
        initComponents();
        this.setLocationRelativeTo(null);
        //lblMain.setIcon(new ImageIcon("D:\\JavaO\\J2_S_P0001\\src\\j2_s_p0001\\image3.png"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnImage1 = new javax.swing.JButton();
        btnImage2 = new javax.swing.JButton();
        btnImage3 = new javax.swing.JButton();
        btnImage4 = new javax.swing.JButton();
        btnImage5 = new javax.swing.JButton();
        lblMain = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/j2_s_p0001/image1.png"))); // NOI18N
        btnImage1.setFocusable(false);
        btnImage1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImage1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImage1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnImage1);

        btnImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/j2_s_p0001/image2.png"))); // NOI18N
        btnImage2.setFocusable(false);
        btnImage2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImage2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImage2ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnImage2);

        btnImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/j2_s_p0001/image3.png"))); // NOI18N
        btnImage3.setFocusable(false);
        btnImage3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImage3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImage3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImage3ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnImage3);

        btnImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/j2_s_p0001/image4.png"))); // NOI18N
        btnImage4.setFocusable(false);
        btnImage4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImage4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImage4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImage4ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnImage4);

        btnImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/j2_s_p0001/image5.png"))); // NOI18N
        btnImage5.setFocusable(false);
        btnImage5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImage5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImage5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImage5ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnImage5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMain, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImage1ActionPerformed

        ImageIcon dabIcon = new ImageIcon("D:\\JavaO\\J2_S_P0001\\src\\j2_s_p0001\\image1.png");
        
        Image dabImage = dabIcon.getImage();
        Image modifiedDabImage = dabImage.getScaledInstance(634, 348, Image.SCALE_SMOOTH);
        dabIcon = new ImageIcon(modifiedDabImage);
        lblMain.setIcon(dabIcon);
       
    }//GEN-LAST:event_btnImage1ActionPerformed

    private void btnImage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImage2ActionPerformed
         ImageIcon dabIcon = new ImageIcon("D:\\JavaO\\J2_S_P0001\\src\\j2_s_p0001\\image2.png");
        
        Image dabImage = dabIcon.getImage();
        Image modifiedDabImage = dabImage.getScaledInstance(634, 348, Image.SCALE_SMOOTH);
        dabIcon = new ImageIcon(modifiedDabImage);
        lblMain.setIcon(dabIcon);
    }//GEN-LAST:event_btnImage2ActionPerformed

    private void btnImage3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImage3ActionPerformed
         ImageIcon dabIcon = new ImageIcon("D:\\JavaO\\J2_S_P0001\\src\\j2_s_p0001\\image3.png");
        
        Image dabImage = dabIcon.getImage();
        Image modifiedDabImage = dabImage.getScaledInstance(634, 348, Image.SCALE_SMOOTH);
        dabIcon = new ImageIcon(modifiedDabImage);
        lblMain.setIcon(dabIcon);
    }//GEN-LAST:event_btnImage3ActionPerformed

    private void btnImage4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImage4ActionPerformed
         ImageIcon dabIcon = new ImageIcon("D:\\JavaO\\J2_S_P0001\\src\\j2_s_p0001\\image4.png");
        
        Image dabImage = dabIcon.getImage();
        Image modifiedDabImage = dabImage.getScaledInstance(634, 348, Image.SCALE_SMOOTH);
        dabIcon = new ImageIcon(modifiedDabImage);
        lblMain.setIcon(dabIcon);
    }//GEN-LAST:event_btnImage4ActionPerformed

    private void btnImage5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImage5ActionPerformed
         ImageIcon dabIcon = new ImageIcon("D:\\JavaO\\J2_S_P0001\\src\\j2_s_p0001\\image5.png");
        
        Image dabImage = dabIcon.getImage();
        Image modifiedDabImage = dabImage.getScaledInstance(634, 348, Image.SCALE_SMOOTH);
        dabIcon = new ImageIcon(modifiedDabImage);
        lblMain.setIcon(dabIcon);
    }//GEN-LAST:event_btnImage5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(J2_S_P0001.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(J2_S_P0001.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(J2_S_P0001.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(J2_S_P0001.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new J2_S_P0001().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImage1;
    private javax.swing.JButton btnImage2;
    private javax.swing.JButton btnImage3;
    private javax.swing.JButton btnImage4;
    private javax.swing.JButton btnImage5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblMain;
    // End of variables declaration//GEN-END:variables
}
